### ISSUE TITLE
显示优化，配置编辑页面，使用鼠标选中配置时，颜色不明显

### ISSUE THREAD

**Issue by ZhicongZheng** [r-nacos/rnacos-console-web#12]
<img width="690" alt="image" src="https://github.com/user-attachments/assets/5fff4faf-38c9-433a-8b17-2086383bb9e5">
我这里实际上选中了最后一行，但是背景颜色太深了，看不出来选中了哪些
另外搜索配置时，关闭按钮太小了，而且颜色不明显

**Comment by heqingpan** [comment]
需求已收到，后面会抽空处理。

**Comment by heqingpan** [comment]
v0.5.21版本已支持
