### ISSUE TITLE
调整API请求超时

### ISSUE THREAD

**Issue by a8851625** [r-nacos/rnacos-console-web#7]
兄弟，为啥API默认设置超时为1000毫秒？

也太苛刻了吧

**Comment by heqingpan** [comment]
> 兄弟，为啥API默认设置超时为1000毫秒？
> 
> 也太苛刻了吧

你是指哪个模块的接口？
对应日志方便提供下吗？

**Comment by heqingpan** [comment]
我看错了，以为是后端的配置。

你是指前端超时配置是吗？ 
我得看看代码确认下。

1秒确实比较苛刻，如果有这个限制，可以再放宽。

**Comment by a8851625** [comment]
现在是/rnacos/login的时候调用验证码和登录接口都会提示1000ms超时；

搜了一下：
src/utils/request.ts#L25
src/utils/request.ts#L36

都有写死的`timeout: 1000,`

**Comment by a8851625** [comment]
补充：

![image](https://github.com/r-nacos/rnacos-console-web/assets/10271628/27a43795-cda2-4133-8303-d3dddb73b067)

api/console/login/login
api/console/login/captcha

**Comment by heqingpan** [comment]
收到，我在下个版本调拨一下。
本周末有计划发一个版本。

**Comment by heqingpan** [comment]
v0.5.13版本已解决
