### ISSUE TITLE
can rnacos-console-web with nacos ?

### ISSUE THREAD

**Issue by shalk** [r-nacos/rnacos-console-web#8]
Though rnacos-console-web is part of rnacos.

Can rnacos-console-web work with  Nacos ?

**Comment by heqingpan** [comment]
Rnacos-console-web is part of rnacos.
It currently has no plans to support working with nacos

The main reason:
1. nacos has its own front end, and it doesn't seem necessary to use rnacos-console-web;
2. Even if rnacos-console-web supports nacos, it doesn't make much sense that it can't be packaged and distributed with nacos;
3. The simultaneous adaptation of rnacos-console-web to rnacos and nacos requires more additional development work; There are currently no additional resources devoted to this part of the work;

**Comment by shalk** [comment]
1. Nacos backend is solid impelment, but nacos frond end is couple with the backend. 

2. So If a decoupled console which is comunicate with nacos with openapi  that would be better. The console could be distributed independent.

3. If the api is standard, it will not take more  additional  development work.

Just some tips

**Comment by heqingpan** [comment]
In fact, rnacos-console-web initially wanted to use openapi as much as possible, but later found that the existing openapi did not meet the functions of rnacos-console-web, and then switched to a separate api.

So I'll stick with the previous point.
